name: ComplianceSendModule
on: [pull_request]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
    send-to-compliance:
        name: Send to Compliance
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Get repo name
              id: get_repo_name
              run: |
                echo REPO_NAME=$(echo ${{ github.workspace }} | cut -d / -f 5) >> $GITHUB_OUTPUT
            - name: Get branch name
              id: get_branch_name
              run: |
                echo BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} >> $GITHUB_OUTPUT
            - name: Zip Folder
              run: |
                cd ..
                zip -r -q module.zip ${{ steps.get_repo_name.outputs.REPO_NAME }} -x module.zip
            - name: Get OAUTH token from oauth.prestashop.com
              uses: ./actions/auth-compliance
              id: get_oauth_token
              with:
                token-uri: ${{ secrets.OAUTH_TOKEN_URI }}
                cookie: ${{ secrets.OAUTH_COOKIE }}
                client-id: ${{ secrets.OAUTH_CLIENT_ID }}
                client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
                grant-type: ${{ secrets.OAUTH_GRANT_TYPE }}
                audience: ${{ secrets.OAUTH_AUDIENCE }}
                scope: ${{ secrets.OAUTH_SCOPE }}
            - name: Get workflow ID to get reports
              id: get_workflow_id
              run: |
                echo RUNID=$(gh api repos/PrestaShopSellerExtensions/${{ steps.get_repo_name.outputs.REPO_NAME }}/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq -r '.check_runs[] | select(.name == "get reports") | .html_url | capture("/runs/(?<number>[0-9]+)/jobs") | .number' | sed 's/"//g' | head -n 1) >> $GITHUB_OUTPUT
            - name: "Send zip to orchestrator"
              id: send_zip
              run: |
                curl --location --request POST "${{ secrets.COMPLIANCE_BASE_URI }}/orchestrator/v1/scan" \
                    --header "Connection: keep-alive" \
                    --header "Content-Type: multipart/form-data" \
                    --oauth2-bearer ${{ steps.get_oauth_token.outputs.token }} \
                    --form 'module=@./../module.zip' \
                    --form 'callback[method]="post"' \
                    --form 'callback[uri]="https://api.github.com/repos/PrestaShopSellerExtensions/${{ steps.get_repo_name.outputs.REPO_NAME }}/actions/runs/${{ steps.get_workflow_id.outputs.RUNID }}/rerun"' \
                    --form 'callback[headers][0][0]="Accept"' \
                    --form 'callback[headers][0][1]="application/vnd.github+json"' \
                    --form 'callback[headers][1][0]="X-GitHub-Api-Version"' \
                    --form 'callback[headers][1][1]="2022-11-28"' \
                    --form 'callback[headers][2][0]="Authorization"' \
                    --form 'callback[headers][2][1]="Bearer ${{ secrets.PAT }}"' \
                    --output scan.json
                jq --color-output . scan.json | less -R
