name: ComplianceSendModule
on: [pull_request]

jobs:
  compliance-send:
      name: send module for scan
      runs-on: ubuntu-latest
      steps:
          - name: Get repo name
            id: get_repo_name
            run: |
              echo REPO_NAME=$(echo ${{ github.workspace }} | cut -d / -f 5) >> $GITHUB_OUTPUT && exit 0
          - name: Get branch name
            id: get_branch_name
            run: |
              echo BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} >> $GITHUB_OUTPUT && exit 0
          - name: send to compliance orchestrator
            uses: PrestaShopCorp/github-action-compliance-send@v1.0       
            with:
              repository_name: ${{ steps.get_repo_name.outputs.REPO_NAME }}
              branch_name: ${{ steps.get_branch_name.outputs.BRANCH }}
              token-uri: ${{ secrets.OAUTH_TOKEN_URI }}             
              cookie: ${{ secrets.OAUTH_COOKIE }}                 
              client-id: ${{ secrets.OAUTH_CLIENT_ID }}                  
              client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}                 
              grant-type: ${{ secrets.OAUTH_GRANT_TYPE }}                  
              audience: ${{ secrets.OAUTH_AUDIENCE }}                   
              scope: ${{ secrets.OAUTH_SCOPE }}                  
              compliance-base-uri: ${{ secrets.COMPLIANCE_BASE_URI }}  
              pat: ${{ secrets.PAT }}  
              