name: ComplianceSendModule
on:
  workflow_call:
    inputs:
      workflow-report-id:
        required: true
        type: string
    secrets:
      OAUTH_TOKEN_URI:
        required: true
      OAUTH_COOKIE:
        required: true
      OAUTH_CLIENT_ID:
        required: true
      OAUTH_CLIENT_SECRET:
        required: true
      OAUTH_GRANT_TYPE:
        required: true
      OAUTH_AUDIENCE:
        required: true
      OAUTH_SCOPE:
        required: true
      GH_TOKEN:
        required: true
      COMPLIANCE_BASE_URI:
        required: true

jobs:
    send-to-compliance:
        name: Send to Compliance
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Get repo name
              id: get_repo_name
              run: |
                echo REPO_NAME=$(echo ${{ github.workspace }} | cut -d / -f 5) >> $GITHUB_OUTPUT
            - name: Zip Folder
              run: |
                cd ..
                zip -r -q module.zip ${{ steps.get_repo_name.outputs.REPO_NAME }} -x module.zip
            - name: Get OAUTH token from oauth.prestashop.com
              uses: ./actions/auth-compliance
              id: get_oauth_token
              with:
                token-uri: ${{ secrets.OAUTH_TOKEN_URI }}
                cookie: ${{ secrets.OAUTH_COOKIE }}
                client-id: ${{ secrets.OAUTH_CLIENT_ID }}
                client-secret: ${{ secrets.OAUTH_CLIENT_SECRET }}
                grant-type: ${{ secrets.OAUTH_GRANT_TYPE }}
                audience: ${{ secrets.OAUTH_AUDIENCE }}
                scope: ${{ secrets.OAUTH_SCOPE }}
            - name: "Send zip to orchestrator"
              id: send_zip
              run: |
                curl --location --request POST "${{ secrets.COMPLIANCE_BASE_URI }}/orchestrator/v1/scan" \
                    --header "Connection: keep-alive" \
                    --header "Content-Type: multipart/form-data" \
                    --oauth2-bearer ${{ steps.get_oauth_token.outputs.token }} \
                    --form 'module=@./../module.zip' \
                    --form 'callback[method]="post"' \
                    --form 'callback[uri]="https://api.github.com/repos/PrestaShopSellerExtensions/${{ steps.get_repo_name.outputs.REPO_NAME }}/actions/runs/${{ inputs.workflow-report-id }}/rerun"' \
                    --form 'callback[headers][0][0]="Accept"' \
                    --form 'callback[headers][0][1]="application/vnd.github+json"' \
                    --form 'callback[headers][1][0]="X-GitHub-Api-Version"' \
                    --form 'callback[headers][1][1]="2022-11-28"' \
                    --form 'callback[headers][2][0]="Authorization"' \
                    --form 'callback[headers][2][1]="Bearer ${{ secrets.GH_TOKEN }}"' \
                    --output scan.json
                jq --color-output . scan.json | less -R
