name: Validator tests
on: [pull_request]
jobs:
  validator-tests:
    name: send test to validator
    runs-on: ubuntu-latest
    steps:
        - name: get current branch name
          id: vars
          run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
        - name: send module to validator
          uses: PrestaShopCorp/github-action-validator@dev
          env:
            VALIDATOR_API_KEY: ${{ secrets.VALIDATOR_API_KEY }}
          with:
            github_link: PrestaShopSellerExtensions/${{ github.event.repository.name }}
            github_branch: ${{ steps.vars.outputs.short_ref }}